### ISSUE TITLE
Sass Syntax Problem

### ISSUE THREAD

**Issue by optikfluffel** [SC5/sc5-styleguide#479] opened 2015-02-25 23:52 UTC
Hey :)

I've stumbled across a little problem using `.sass` files and trying to copy your [color example](https://github.com/SC5/sc5-styleguide/blob/master/lib/app/sass/app.scss#L38-L49). I only got that to work only when I added the `;` which don't really belong there when using sass.
Do you know what's wrong there?

Thanks

**Comment by junaidrsd** [comment] 2015-03-23 11:37
Hey,
Can't reproduce it or it might be fixed at some point.

**Comment by cyberixae** [comment] 2015-03-25 15:54
I am closing this. Based on previous comment. Feel free to reopen the issue if it is still a problem.

**Closed by cyberixae** 2015-03-25 15:54 UTC
Labels: bug
