### ISSUE TITLE
styleguide_helper_elements.css not loading - wrong path

### ISSUE THREAD

**Issue by jamieholliday** [SC5/sc5-styleguide#799] opened 2015-09-23 15:36 UTC
I have this setup using gulp but styleguide_helper_elements.css file is not loading. 

It looks like the path in index.html is wrong.

 ```
<script type="text/ng-template" id="userStyles.html">
    <style>
      @import url('/styleguide.css');
      @import url('/styleguide_pseudo_styles.css');
      @import url('/css/styleguide_helper_elements.css');
    </style>
  </script>
```
looking for file in /css folder but file is in the same path as the other 2 css files above

**Comment by kraftner** [comment] 2015-09-24 08:19
duplicate of #716

**Closed** 2015-09-24 16:09 UTC
