### ISSUE TITLE
Can only load one directive at a time

### ISSUE THREAD

**Issue by cupojoe** [SC5/sc5-styleguide#517] opened 2015-03-19 04:32 UTC
Creating a second directive overwrites the first one. Even if they are in different modules. The files for the second directive don't load but they are in the angular config array.

**Comment by junaidrsd** [comment] 2015-03-25 13:57
The problem is <a href="https://github.com/SC5/sc5-styleguide/blob/master/lib/app/js/app.js#L49"> HERE </a> in lib/app/js/app.js which is preventing to inject more directives. It can be fixed by replacing loadLazyModule:

           loadLazyModule: function($ocLazyLoad) {
            if (window.filesConfig && window.filesConfig.length) {
              var fileNames = [];
              angular.forEach(window.filesConfig, function(file) {
                fileNames.push(file.name);
              });
              return $ocLazyLoad.load(fileNames);
            }
          }

**Comment by junaidrsd** [comment] 2015-03-25 14:07
I wonder what would be the best way to write test case for this problem?

**Comment by cupojoe** [comment] 2015-03-26 21:13
Yeah, for now I patched my local copy with a loop through all the directives and it works like charm. Something very similar to what you did but with vanilla JS instead of angular.forEach.

**Closed** 2015-03-30 12:26 UTC
Labels: bug, pending release
