### ISSUE TITLE
Reference >=10 matches and groups on Reference "1"

### ISSUE THREAD

**Issue by bfowle** [SC5/sc5-styleguide#454] opened 2015-01-30 21:12 UTC
Defining "Styleguide X.Y" where X is 1, 10, 100, etc. these will all group on the "1" reference.
e.g.
// Styleguide 1.1
// Styleguide 11.1

**Comment by jpbackman** [comment] 2015-01-30 21:52
Hi,

This is a duplicate of [#447](https://github.com/SC5/sc5-styleguide/issues/447), which has already been fixed and will be released with the next version, most likely next week.

I'll reopen that one so others will find it without having to look at the closed issues.

**Closed by jpbackman** 2015-01-30 21:52 UTC
Labels: duplicate
