### ISSUE TITLE
Using 3 or more modifiers gives error

### ISSUE THREAD

**Issue by dawidk92** [SC5/sc5-styleguide#1037] opened 2016-11-18 12:39 UTC
It would be nice if :active will work the same as :hover in KSS notation.

// Button
//
// default - default button
// :hover - hover button
// :active - active button

Right now ':active' throws error:
"Styleguide generation failed
Error: TypeError: varName.substring is not a function in $file"

**Comment by varya** [comment] 2016-12-27 16:09
Hey. I suspect that the problem is not `:active` modifier but using 3 or more modifiers. If you change `:active` to anything like `.class - Smth`, is there the same problem? If there is, then the fix will be soon merged https://github.com/SC5/sc5-styleguide/pull/1050

**Comment by dawidk92** [comment] 2016-12-28 09:03
Yep, you're right. Error occurs when there are used 2 or more pseudo classes.
:active works alone but with use of :hover it doesn't any more

**Closed** 2016-12-28 09:33 UTC
