### ISSUE TITLE
"npm install -g sc5-styleguide" error with node 0.11

### ISSUE THREAD

**Issue by pdnellius** [SC5/sc5-styleguide#370] opened 2014-12-23 14:54 UTC
Getting an error when I try and install via npm:

```
Binary downloaded and installed at /Users/pete.nellius/.nvm/v0.11.14/lib/node_modules/sc5-styleguide/node_modules/kss/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/pete.nellius/.nvm/v0.11.14/lib/node_modules/sc5-styleguide/node_modules/kss/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pete.nellius/.nvm/v0.11.14/lib/node_modules/sc5-styleguide/node_modules/kss/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/pete.nellius/.nvm/v0.11.14/bin/node" "/Users/pete.nellius/.nvm/v0.11.14/bin/npm" "install" "-g" "sc5-styleguide"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
```

**Comment by varya** [comment] 2015-01-16 08:45
Maybe this is a node bug. I asked them https://github.com/joyent/node/issues/9040

**Comment by junaidrsd** [comment] 2015-04-07 09:46
As they replied joyent/node#9040 the issue is with node-sass see sass/node-sass#550 and sass/node-sass#517.

I'm closing it but it can be reopened.

**Closed by junaidrsd** 2015-04-07 09:46 UTC
Labels: bug
